ARG NODE_VERSION=18.20.3
FROM node:${NODE_VERSION}-alpine

ARG PORT
ARG JWT_SECRET
ARG PROJECT_ID
ARG SERVICE_ACCOUNT_PATH

ENV PORT=PORT
ENV JWT_SECRET=JWT_SECRET
ENV PROJECT_ID=PROJECT_ID
ENV SERVICE_ACCOUNT_PATH=SERVICE_ACCOUNT_PATH

WORKDIR /usr/src/app

COPY . .

RUN npm install

EXPOSE 3000

CMD npm start